---  
title: Conditional Probability
output: 
  html_document
---

&nbsp;


## Conditional Probability

### Definition

* Probabilities change when _conditioning_ on additional information.
* Probability of \(A\) given \(B\):

$$P(A | B) = \frac{P(A \cap B)}{P(B)}$$


* If \(A\) and \(B\) are independent:

$$P(A ~|~ B) = \frac{P(A \cap B)}{P(B)} = P(A)$$

&nbsp;

### Conditioning matters

* Probability of being struck by lightning vs. probability of being struck by lightning, provided you go out in the woods in a heavy thunderstorm
* Probability of contracting rare hereditary disease XYZ vs. probability of contracting rare hereditary disease XYZ, given parents have it

&nbsp;

### Bayes Theorem


$$P(A ~|~ B) = \frac{P(B|A) * P(A)}{P(B)}$$

where

* Prior probability \(P(A)\)
* Likelihood \(P(B|A)\)
* Evidence \(P(B)\)
* Posterior probability \(P(A|B)\)

&nbsp;

Let's do the genius thing again.

$P(genius ~|~ test\>positive) = \frac{P(test\>positive|genius) * P(genius)}{P(test\>positive)} =  \frac{P(test\>positive|genius) * P(genius)}{P(test\>positive|genius) * P(genius) + P(test\>positive|not\>a\>genius) * P(not\>a\>genius)}$

$P(genius ~|~ test\>positive) = \frac{0.92 * 0.001}{0.92 * 0.001 + (1 - 0.99) * 0.999} = 0.08$


&nbsp;
