---
title: "Confidence intervals"
output: html_document
---

## Confidence Intervals

### From the CLT to confidence intervals


According to the CLT, the sample mean, {$$}\bar X{/$$},
is approximately normal with mean {$$}\mu{/$$} and standard
deviation {$$}\sigma / \sqrt{n}{/$$}. Furthermore,

{$$}\mu + 2 \sigma /\sqrt{n}{/$$}

 is pretty far out in the tail
(only 2.5% of a normal being larger than 2 sds in the tail).
Similarly,

{$$}\mu - 2 \sigma /\sqrt{n}{/$$}

is pretty far in the left tail (only 2.5% chance of a normal being smaller than
2 standard deviations in the tail). So the probability
{$$}\bar X{/$$} is bigger than {$$}\mu + 2 \sigma / \sqrt{n}{/$$}
or smaller than {$$}\mu - 2 \sigma / \sqrt{n}{/$$} is 5%.
Or equivalently, the probability that these limits contain {$$}\mu{/$$}
is 95%. The quantity:

{$$}\bar X \pm 2 \sigma /\sqrt{n}{/$$}

is called a 95% interval for {$$}\mu{/$$}.
The 95% refers to the fact that if one were to repeatedly
get samples of size {$$}n{/$$}, about 95% of the intervals obtained
would contain {$$}\mu{/$$}. The 97.5th quantile is 1.96 (so I rounded to 2 above).
If instead of a 95% interval, you wanted a 90% interval, then
 you want (100 - 90) / 2 = 5% in each tail. Thus your replace the 2 with
 the 95th percentile, which is 1.645.






## CI caveats

* 95 % confidence is a confidence that in the long-run 95 % of the CIs will include the population mean. It is a confidence in the algorithm and not a statement about a single CI.
* In frequentist terms the CI either contains the population mean or it does not. 
* Relationship to p-values: if an effect is statistically different ( p < 0.05) from 0 in a
two-sided t -test with an alpha of .05, the 95% CI for the mean difference between two
groups will not include zero.
* Visualization: http://rpsychologist.com/d3/CI/

## Calculation of CI
* CI for a mean, using the t distribution:
##tbd


## Prediction intervals
* Even though 95% of future confidence intervals will contain the true parameter, a 95%
confidence interval will not contain 95% of future individual observations.
* It is always much wider than a confidence interval. The reason is
7that individual observations can vary substantially, but means of future samples (which
fall within a normal confidence interval 95% of the time) will vary much less

## Calculation of CI
* CI for a mean, using the t distribution:
##tbd
Standard Error (SE) = σ*√(1+1/N)

## One thing people find difficult to understand is why a 95% confidence interval does not
provide us with the interval where 95% of future means will fall. The % of means that falls
within a single confidence interval is called the capture percentage. A 95% confidence
interval is only a 95% capture percentage when the statistic (such as an effect size) you
observe in a single sample happens to be exactly the same as the true parameter. This
situation is illustrated in the picture below. The observed effect size (dot) falls exactly on
the true effect size (vertical dotted line). In this case, and only in this case , 95% of future
means will fall within this 95% confidence interval.
So, the percentage of future means that fall within a single
confidence interval depends upon which single confidence interval you happened to
observe! In the long run, a 95% CI has an 83.4% capture probability (Cumming &
Maillardet, 2006).
The simulation
returns the number of CI that contains the mean (which should be 95% in the long run).
The simulation also returns the % of means from future studies that fall within the 95%
of the original study, or the capture percentage. It differs from (and is often lower, but
sometimes higher, than) the confidence interval.
