---
title: "Hypothesis testing, p-values, and confidence intervals"
output: html_document
---

## Hypothesis testing, p-values, and confidence intervals

### The meaning of p

* Hypothesis testing, p-values, and confidence intervals are all related.
* Looking at the output of a $t$ test ...

```{r}
set.seed(1024)
population_mean <- 1000
simulation_mean <- 1002
sd <- 2
n <- 9
data <- rnorm(n, mean = simulation_mean, sd = sd)
t.test(data, alternative = 'two.sided', mu = population_mean, conf.level = 0.95)
```

* we have that:
    + under $H_0$, when $\mu$ = 1000, the sample mean obtained corresponds to a $t$ value of $t$ = 1.4002
    + the respective _p-value_ is the probability, under $H_0$, of obtaining a $t$ value as extreme or more extreme than that
* As we did a two-sided test, this means that the probability of obtaining a $t \ge$ 1.4002 or a $t \le$ -1.4002 is 0.199, under the assumption the true mean is 1000
* As this p-value is greater than 0.05, we cannot reject $H_0$

`

### P-values: relationship to confidence intervals

* If an effect is statistically different from the value assumed under $H_0$ in a two-sided $t$-test with an alpha of .05 (p = .05), the 95% confidence interval will not include that value.
* In our example, we have that the 95% confidence interval ranges from 999.18 to 1003.34 and thus, includes 1000.

* Thus, the following are all synonymous:

    + p < the chosen $\alpha$
    + the effect is significant (on the chosen $\alpha$ - level)
    + the $1-\alpha$ % confidence interval does not include the value assumed under $H_0$
    
